# Generated by Django 4.2.2 on 2023-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_vendorprofile_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Code'),
        ),
    ]
