# Generated by Django 4.2.2 on 2023-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customerprofile_image_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/cover'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_second',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_second',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Numbr 2'),
        ),
    ]
