# Generated by Django 4.2.2 on 2023-07-05 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_vendorapply_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorRequest',
        ),
        migrations.AddField(
            model_name='vendorapply',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
