# Generated by Django 4.2.3 on 2023-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categories_icon_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='total_sales',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
