# Generated by Django 4.2.3 on 2023-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categories_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='total_sales',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
