# Generated by Django 4.2.3 on 2023-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_categories_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categorY_icons'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categorY_images'),
        ),
    ]
