# Generated by Django 4.2.3 on 2023-07-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcut_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/prioduct_gallery_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='shop.product')),
            ],
        ),
    ]
