# Generated by Django 4.2.3 on 2023-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
