# Generated by Django 4.2.3 on 2023-07-18 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0014_wishlistmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishListModel',
            new_name='WishList',
        ),
    ]
